include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - directives_ordering

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

errors:
  strict-casts: error
  strict-inference: error
  strict-raw-types: error
  directives_ordering: error
