name: func_dart_core
description: Functional Dart provides tools for writing functional code in Dart, emphasizing immutability, function composition, type safety, and avoiding the `dynamic` type.
version: 0.5.1
repository: https://github.com/JKWA/func_dart_core
homepage: https://jkwa.github.io/func_dart_core/index.html
issue_tracker: https://github.com/JKWA/func_dart_core/issues
license: MIT

environment:
  sdk: ^3.0.6

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.0
