name: functional_dart
description: A library for functional programming
version: 0.1.0
repository: https://github.com/JKWA/functional_dart
homepage: https://jkwa.github.io/functional_dart/index.html
issue_tracker: https://github.com/JKWA/functional_dart/issues
license: MIT

environment:
  sdk: ^3.0.6

dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.0
