name: Lint and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      # Verify that the Dart code follows the Dart style guide
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Analyze the Dart code for potential errors and warnings
      - name: Analyze project source
        run: dart analyze --fatal-infos

      # Run unit tests
      - name: Run tests
        run: dart test
